import ApplicationFoundation
import ApplicationLifeCycleServiceInterface

extension ExampleApplicationScope: ApplicationLifeCycleListenerProvider {}
extension ExampleApplicationScope: ApplicationLifeCycleServiceProvider {}